eureka:
 client:   
  service-url:
   defaultZone: http://localhost:9091/eureka/
spring:
 output:
  ansi:
   enabled: always
 datasource:
  url: jdbc:h2:mem:studentdb
  username: chandan
  password: chandan
  driverClassName: org.h2.Driver
 jpa:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect  
management:
  tracing:
    sampling:
      probability: 1.0


  