eureka:
 client:   
  service-url:
   defaultZone: http://localhost:9091/eureka/
 instance:
  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 2
spring:
 output:
  ansi:
   enabled: always
 datasource:
  url: jdbc:h2:mem:paymentdb
  username: chandan
  password: chandan
  driverClassName: org.h2.Driver
 jpa:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
 security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999
   
management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'