eureka:
 client:   
  service-url:
   defaultZone: http://localhost:9091/eureka/
 instance:
  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 2
spring:
 output:
  ansi:
   enabled: always
 datasource:
  url: jdbc:h2:mem:studentdb
  username: chandan
  password: chandan
  driverClassName: org.h2.Driver
 jpa:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      student-service:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


  